# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)

PKG_NAME="agentsight"
PKG_VERSION="${AGENTSIGHT_VERSION:-1.0.3}"
PKG_LICENSE="MIT"
PKG_SITE="https://github.com/weihuoya/agentsight"
PKG_URL=""
PKG_DEPENDS_TARGET="toolchain cargo:host rust elfutils zlib"
PKG_LONGDESC="System-wide AI agent profiling and monitoring with eBPF"
PKG_TOOLCHAIN="manual"

AGENTSIGHT_SOURCE_DIR="${AGENTSIGHT_SOURCE_DIR:-${ROOT}/agentsight}"

unpack() {
  rm -rf "${PKG_BUILD}"
  mkdir -p "$(dirname ${PKG_BUILD})"
  cp -PRf "${AGENTSIGHT_SOURCE_DIR}" "${PKG_BUILD}"
}

make_target() {
  set -e
  cd ${PKG_BUILD}

  # If the workflow wants to use a shared cargo registry cache, write a minimal
  # cargo config that keeps the ROCKNIX target linker configuration and also
  # provides a host linker for proc-macro / build-script crates (the container
  # has 'gcc' but not the default 'cc' linker that cargo expects).
  if [ -n "${CARGO_HOME_OVERRIDE}" ]; then
    mkdir -p "${CARGO_HOME_OVERRIDE}"
    HOST_TRIPLE="$(rustc -vV | sed -n 's/^host: //p')"
    cat > "${CARGO_HOME_OVERRIDE}/config.toml" <<EOF
[target.${TARGET_NAME}]
linker = "${TARGET_PREFIX}gcc"

[target.${HOST_TRIPLE}]
linker = "gcc"
EOF
    export CARGO_HOME="${CARGO_HOME_OVERRIDE}"
  fi

  # -------------------------------------------------------------------------
  # Build BPF loaders for the target. The eBPF objects (.bpf.o) and generated
  # skeleton headers (.skel.h) are already produced by the workflow on the
  # host (architecture-independent), so we only need to rebuild the target
  # libbpf.a and the user-space loader binaries here.
  # -------------------------------------------------------------------------
  cd bpf
  make ARCH=arm64 \
       CROSS_COMPILE=${TARGET_PREFIX} \
       CC="${CC}" \
       -j${CONCURRENCY_MAKE_LEVEL} \
       .output/libbpf.a

  # The host workflow already generated the .bpf.o objects and .skel.h skeletons
  # with a host clang that supports the bpf target. The ROCKNIX cross toolchain
  # clang does not have the bpf target, and the container has no host bpftool, so
  # we must prevent make from trying to rebuild them here. Provide a stub bpftool
  # and mark both the .bpf.o and .skel.h files as 'old' with -o so make uses the
  # prebuilt artifacts and only recompiles the target userspace loader binaries.
  mkdir -p .output/bpftool/bootstrap
  cat > .output/bpftool/bootstrap/bpftool-stub <<'EOF'
#!/bin/sh
# Stub: skeletons and BPF objects are already generated on the host.
exit 0
EOF
  chmod +x .output/bpftool/bootstrap/bpftool-stub

  make ARCH=arm64 \
       CROSS_COMPILE=${TARGET_PREFIX} \
       CC="${CC}" \
       BPFTOOL=.output/bpftool/bootstrap/bpftool-stub \
       -j${CONCURRENCY_MAKE_LEVEL} \
       -o .output/process.bpf.o \
       -o .output/sslsniff.bpf.o \
       -o .output/stdiocap.bpf.o \
       -o .output/process.skel.h \
       -o .output/sslsniff.skel.h \
       -o .output/stdiocap.skel.h \
       process sslsniff stdiocap

  cd ${PKG_BUILD}

  # Vendor the loader binaries into the Rust capture crate so they are embedded
  # into the final agentsight binary.
  ${STRIP} bpf/process bpf/sslsniff bpf/stdiocap
  mkdir -p agentsight-capture/vendor/bpf
  cp -f bpf/process agentsight-capture/vendor/bpf/
  cp -f bpf/sslsniff agentsight-capture/vendor/bpf/
  cp -f bpf/stdiocap agentsight-capture/vendor/bpf/

  # Build the Rust binaries. Frontend assets and the ext/vis runtime are
  # already generated by the workflow and copied into the source tree before
  # this package is built. C dependencies (e.g. ring) use the cc crate, which
  # looks for target-specific env vars in *lowercase* with underscores:
  #   CC_aarch64_rocknix_linux_gnu, CFLAGS_aarch64_rocknix_linux_gnu, etc.
  # Make sure these point to the ROCKNIX cross compiler for target crates.
  # -------------------------------------------------------------------------
  CC_TARGET_VAR="CC_$(echo "${TARGET_NAME}" | tr '-' '_')"
  CFLAGS_TARGET_VAR="CFLAGS_$(echo "${TARGET_NAME}" | tr '-' '_')"
  AR_TARGET_VAR="AR_$(echo "${TARGET_NAME}" | tr '-' '_')"
  eval "export ${CC_TARGET_VAR}=\"${CC}\""
  eval "export ${CFLAGS_TARGET_VAR}=\"${CFLAGS}\""
  eval "export ${AR_TARGET_VAR}=\"${AR}\""
  export TARGET_CC="${CC}"
  export TARGET_CFLAGS="${CFLAGS}"
  export TARGET_AR="${AR}"
  export CC_ENABLE_DEBUG_OUTPUT=1

  # Enable sccache if the workflow mounted it into the container.
  if [ -x "/work/rocknix/.sccache/sccache" ]; then
    export RUSTC_WRAPPER="/work/rocknix/.sccache/sccache"
    echo "AGENTSIGHT_DEBUG: RUSTC_WRAPPER=${RUSTC_WRAPPER}" >&2
  fi

  echo "AGENTSIGHT_DEBUG: TARGET_NAME=${TARGET_NAME}" >&2
  echo "AGENTSIGHT_DEBUG: TARGET=${TARGET}" >&2
  echo "AGENTSIGHT_DEBUG: HOST_CC=${HOST_CC}" >&2
  echo "AGENTSIGHT_DEBUG: HOST_CFLAGS=${HOST_CFLAGS}" >&2
  echo "AGENTSIGHT_DEBUG: HOST_CXXFLAGS=${HOST_CXXFLAGS}" >&2
  echo "AGENTSIGHT_DEBUG: CC_TARGET_VAR=${CC_TARGET_VAR}, value=$(eval "echo \${${CC_TARGET_VAR}}")" >&2
  echo "AGENTSIGHT_DEBUG: CFLAGS_TARGET_VAR=${CFLAGS_TARGET_VAR}, value=$(eval "echo \${${CFLAGS_TARGET_VAR}}")" >&2
  echo "AGENTSIGHT_DEBUG: AR_TARGET_VAR=${AR_TARGET_VAR}, value=$(eval "echo \${${AR_TARGET_VAR}}")" >&2
  echo "AGENTSIGHT_DEBUG: CC=${CC}" >&2
  echo "AGENTSIGHT_DEBUG: CFLAGS=${CFLAGS}" >&2
  echo "AGENTSIGHT_DEBUG: AR=${AR}" >&2
  echo "AGENTSIGHT_DEBUG: TARGET_PREFIX=${TARGET_PREFIX}" >&2

  # headless_chrome pulls in auto_generate_cdp as a build dependency, which in
  # turn uses ureq -> rustls -> ring. Build dependencies are compiled for the
  # host (x86_64), so the cc crate inside ring's build script sees TARGET as the
  # host triple and uses HOST_CC / HOST_CFLAGS. The ROCKNIX framework sets
  # HOST_CFLAGS to x86_64-safe flags but does not export it, and CFLAGS is set
  # to ARM target flags. Export HOST_CFLAGS so host builds use x86_64 flags, and
  # unset CFLAGS inside the cargo subshell so it does not leak into host builds.
  # The three crates share many dependencies; build them in parallel to make use
  # of all available CPU cores.
  build_one() {
    local crate="${1}"
    (
      export HOST_CFLAGS
      export HOST_CXXFLAGS
      unset CFLAGS
      unset CXXFLAGS
      cd "${crate}" && cargo build --target ${TARGET_NAME} --release
    )
  }
  build_one ext/vis &
  build_one collector &
  build_one ext/pprof &
  wait
}

makeinstall_target() {
  mkdir -p ${INSTALL}/usr/bin
  cp "${CARGO_TARGET_DIR}/${TARGET_NAME}/release/agentsight" ${INSTALL}/usr/bin/
  cp "${CARGO_TARGET_DIR}/${TARGET_NAME}/release/agentvis" ${INSTALL}/usr/bin/
  cp "${CARGO_TARGET_DIR}/${TARGET_NAME}/release/agentpprof" ${INSTALL}/usr/bin/
}
