name: Build

on:
  release:
    types: [published]

permissions:
  actions: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-envs:
    environment:
      name: auto
    runs-on: ubuntu-24.04
    outputs:
      OWNER_LC: ${{ steps.set-envs.outputs.OWNER_OUTPUT }}
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - name: Set lowercase owner name
        id: set-envs
        run: |
          OWNER_LC="${OWNER,,}"
          if [ "${OWNER_LC}" != "rocknix" ]; then
            OWNER_LC="rocknix"
          fi
          echo "OWNER_OUTPUT=${OWNER_LC}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}
      - id: generate
        shell: bash
        run: |
          MATRIX='[{"device":"SM8550","project":"ROCKNIX"}]'
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

      - name: Ensure sources release exists
        env:
          GH_TOKEN: ${{ secrets.CACHE_REPO_TOKEN }}
        run: |
          gh release view sources --repo weihuoya/rocknix >/dev/null 2>&1 || \
          gh release create sources --title "Source Mirror" --notes "Auto-uploaded source archives" --prerelease --repo weihuoya/rocknix || true

  build-docker:
    name: Docker
    needs: set-envs
    uses: ./.github/workflows/build-docker-image.yml
    with:
      OWNER_LC: ${{ needs.set-envs.outputs.OWNER_LC }}

  build-devices:
    name: Build Devices
    needs:
      - set-envs
      - build-docker
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.set-envs.outputs.matrix) }}
    uses: ./.github/workflows/build-device.yml
    secrets: inherit
    with:
      PROJECT: ${{ matrix.project }}
      DEVICE: ${{ matrix.device }}
      OWNER_LC: ${{ needs.set-envs.outputs.OWNER_LC }}
      NIGHTLY: yes

